# Generated by Django 2.1.2 on 2018-10-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=9)),
                ('telefono', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('Fecha', models.DateField()),
                ('region', models.TextField(max_length=50)),
                ('ciudad', models.TextField(max_length=50)),
                ('vivienda', models.TextField(max_length=50)),
            ],
        ),
    ]
