# Generated by Django 2.1.2 on 2018-10-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='Fecha',
            new_name='fecha',
        ),
    ]
