# Generated by Django 2.1.2 on 2018-10-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_auto_20181025_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
