# Generated by Django 2.1.2 on 2018-10-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0003_auto_20181025_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='fecha',
            field=models.DateField(),
        ),
    ]
