# Generated by Django 2.1.2 on 2018-11-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0004_auto_20181026_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='contra',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
