# Generated by Django 2.1.2 on 2018-11-09 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0005_formulario_contra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='contra',
        ),
    ]
