# Generated by Django 2.1.2 on 2018-11-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0006_remove_formulario_contra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='region',
            field=models.CharField(choices=[('Tarapacá', 'Región de Tarapacá'), ('Antofagasta', 'Región de Antofagasta'), ('Atacama', 'Región de Atacama'), ('Coquimbo', 'Región de Coquimbo'), ('Valparaiso', 'Región de Valparaíso'), ('Bernardo Ohiggins', 'Región del Libertador General Bernardo OHiggins'), ('Maule', 'Región del Maule'), ('Nuble', 'Región de Ñuble'), ('BioBio', 'Región del Biobío'), ('Araucanía', 'Región de la Araucanía'), ('Los Rios', 'Región de Los Ríos'), ('Los Lagos', 'Región de Los Lagos'), ('Aysen', 'Región de Aysén del General Carlos Ibáñez del Campo'), ('Magallanes', 'Región de Magallanes y de la Antártica Chilena'), ('Santiago', 'Región Metropolitana de Santiago')], default='Santiago', max_length=50),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='vivienda',
            field=models.CharField(choices=[('Patio Grande', 'casa con patio grande'), ('Patio Chico', 'casa con patio pequeño'), ('Sin Patio', 'casa sin patio'), ('Departamento', 'departamento')], default='Patio Grande', max_length=50),
        ),
    ]
