# Generated by Django 2.1.2 on 2018-10-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0005_auto_20181025_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='Foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
