# Generated by Django 2.1.2 on 2018-11-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0008_mascota_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.CharField(choices=[('1', 'Disponible'), ('2', 'No Disponible')], default='Disponible', max_length=1),
        ),
    ]
