# Generated by Django 2.1.2 on 2018-11-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0009_auto_20181110_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Se encuentra Disponible'), ('No disponible', 'No se encuentra Disponible')], default='Disponible', max_length=50),
        ),
    ]
